<template>
    <div>
        <div v-if="type==='view'||type==='view-most'" class="w-100" style="height: 200px">
            <img :id="'img-'+this.design.id+(type==='view'?'-view':type)"
                 class="position-absolute"
                 style="clip: rect(0px, auto, 200px, 0px);width: 200%;margin-left: -50%;"
                 src="">
        </div>

        <img v-else :id="'img-'+this.design.id+(type==='view'?'-view':type)" class="w-100 h-100" src="">

        <div id="main-container" class="px-3 d-none">
            <div :id="'clothing-designer-'+this.design.id+(type==='view'?'-view':type)"></div>
            <br/>
        </div>
    </div>
</template>

<script>
    export default {
        ready() {
        },
        data() {
            return {};
        },
        props: ['type', 'design','ccolor'],
        methods: {},
        mounted() {
            var  colorMap = {1:'red',2:"blue"}
            let _this = this;
            let design =_this.design;
            let $yourDesigner = $("#clothing-designer-" + design.id + (_this.type === 'view' ? '-view' : _this.type)),
                pluginOpts = {
                    mainBarModules: [],
                    productsJSON: getProductJson(design.img,colorMap[_this.ccolor]), //see JSON folder for products sorted in categories
                    customImageParameters: {

                    },
                    actions: {
                        top: [],
                        right: [],
                        bottom: [],
                        left: []
                    }
                },
                yourDesigner = new FancyProductDesigner(
                    $yourDesigner,
                    pluginOpts
                );
            // console.log( "#clothing-designer-" + design.id + (_this.type === 'view' ? '-view' : _this.type))
            //you can listen to events
            $yourDesigner.on('productCreate', async function () {
                yourDesigner.getProductDataURL(function (dataURL) {
                    $('#img-' + design.id + (_this.type === 'view' ? '-view' : _this.type)).attr('src', dataURL);
                });
            });
        }
    };

    export function _get_color() {
        // var colors = ['#0dd4ad', '#ff5050', '#ff80ff', '#ffff1b', '#00b3e6','#FFFFFF'];
        var colors = ['#efda1a'];
        return colors[Math.floor(Math.random() * colors.length)];
    }
    export function getProductJson(img,viewType,color,backprint) {

        console.log(color)
        var $tcolor = color? color: _get_color();

        console.log($tcolor)

        var $front = {
            "title": "Front",
            "thumbnail": "/images/color_shirt/color/front/base.png",
            "elements": [
                {
                    "title": "Shadow",
                    "source": "/images/color_shirt/Shadow3.png",
                    "parameters": {
                        "advancedEditing": false,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": "",
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": false,
                        "colorPrices": {},
                        "colors": "",
                        "copyable": false,
                        "cornerSize": 24,
                        "draggable": false,
                        "evented": false,
                        "excludeFromExport": false,
                        "fill": false,
                        "filter": null,
                        "flipX": false,
                        "flipY": false,
                        "height": 633,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": false,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 0,
                            "price": 0,
                            "colors": "",
                            "removable": false,
                            "draggable": false,
                            "rotatable": false,
                            "resizable": false,
                            "copyable": false,
                            "zChangeable": false,
                            "boundingBox": "",
                            "boundingBoxMode": "inside",
                            "autoCenter": false,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": false,
                            "colorPrices": {},
                            "colorLinkGroup": false,
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": false,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 300,
                            "left": 400,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": null,
                            "scaleMode": "fit",
                            "resizeToW": "0",
                            "resizeToH": "0",
                            "advancedEditing": false,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "customAdds": [],
                            "_isInitial": true,
                            "source": "/images/color_shirt/Shadow3.png",
                            "title": "Shadow",
                            "id": "1588100453287",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 0,
                        "removable": false,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": false,
                        "resizeToH": "0",
                        "resizeToW": "0",
                        "rotatable": false,
                        "scaleMode": "fit",
                        "scaleX": 1,
                        "scaleY": 1,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 300,
                        "topped": false,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 717,
                        "z": -1,
                        "zChangeable": false,
                        "topLeftX": 41.5,
                        "topLeftY": -16.5
                    },
                    "type": "image"
                },
                {
                    "title": "Shirt",
                    "source": "/images/color_shirt/color/front/base.png",
                    "parameters": {
                        "advancedEditing": false,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": "",
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": "base",
                        "colorPrices": {},
                        "colors": [
                            "#b33939"
                        ],
                        "copyable": false,
                        "cornerSize": 24,
                        "draggable": false,
                        "evented": true,
                        "excludeFromExport": false,
                        "fill": $tcolor,
                        "filter": null,
                        "flipX": false,
                        "flipY": false,
                        "height": 539,
                        "isEditable": true,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": false,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 1,
                            "price": 10,
                            "colors": [
                                "#b33939"
                            ],
                            "removable": false,
                            "draggable": false,
                            "rotatable": false,
                            "resizable": false,
                            "copyable": false,
                            "zChangeable": false,
                            "boundingBox": "",
                            "boundingBoxMode": "inside",
                            "autoCenter": false,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": false,
                            "colorPrices": {},
                            "colorLinkGroup": "base",
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": false,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 300,
                            "left": 400,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": null,
                            "scaleMode": "fit",
                            "resizeToW": "0",
                            "resizeToH": "0",
                            "advancedEditing": false,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "customAdds": [],
                            "_isInitial": true,
                            "source": "/images/color_shirt/color/front/base.png",
                            "title": "Shirt",
                            "id": "1588100453424",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 10,
                        "removable": false,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": false,
                        "resizeToH": "0",
                        "resizeToW": "0",
                        "rotatable": false,
                        "scaleMode": "fit",
                        "scaleX": 1,
                        "scaleY": 1,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 300,
                        "topped": false,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 597,
                        "z": -1,
                        "zChangeable": false,
                        "topLeftX": 101.5,
                        "topLeftY": 30.5
                    },
                    "type": "image"
                },
                {
                    "title": "Image Title",
                    "source": img,
                    "parameters": {
                        "advancedEditing": true,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": false,
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": "",
                        "colorPrices": {},
                        "colors": "",
                        "copyable": true,
                        "cornerSize": 24,
                        "draggable": true,
                        "evented": true,
                        "excludeFromExport": false,
                        "fill": false,
                        "filter": "none",
                        "flipX": false,
                        "flipY": false,
                        "height": 200,
                        "isCustom": true,
                        "isEditable": true,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": false,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 3,
                            "price": 4,
                            "colors": "",
                            "removable": true,
                            "draggable": true,
                            "rotatable": true,
                            "resizable": true,
                            "copyable": true,
                            "zChangeable": true,
                            "boundingBox": false,
                            "boundingBoxMode": "inside",
                            "autoCenter": true,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": false,
                            "colorPrices": {},
                            "colorLinkGroup": "",
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": false,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 0,
                            "left": 0,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": "none",
                            "scaleMode": "cover",
                            "resizeToW": "300",
                            "resizeToH": "300",
                            "advancedEditing": true,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "minW": 100,
                            "minH": 100,
                            "maxW": 10000,
                            "maxH": 10000,
                            "minDPI": 72,
                            "maxSize": 10,
                            "isCustom": true,
                            "_addToUZ": null,
                            "_isInitial": false,
                            "source": img,
                            "title": "1588180146.png",
                            "id": "1588180240318",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 4,
                        "removable": true,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": true,
                        "resizeToH": "300",
                        "resizeToW": "300",
                        "rotatable": true,
                        "scaleMode": "cover",
                        "scaleX": 1.5,
                        "scaleY": 1.5,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 300,
                        "topped": false,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 200,
                        "z": -1,
                        "zChangeable": true,
                        "topLeftX": 250,
                        "topLeftY": 150
                    },
                    "type": "image"
                },
                {
                    "title": "Shadow",
                    "source": "/images/color_shirt/Shadow4.png",
                    "parameters": {
                        "advancedEditing": false,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": false,
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": false,
                        "colorPrices": {},
                        "colors": "",
                        "copyable": false,
                        "cornerSize": 24,
                        "draggable": false,
                        "evented": false,
                        "excludeFromExport": false,
                        "fill": false,
                        "filter": null,
                        "flipX": false,
                        "flipY": false,
                        "height": 539,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": true,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 4,
                            "price": 0,
                            "colors": "",
                            "removable": false,
                            "draggable": false,
                            "rotatable": false,
                            "resizable": false,
                            "copyable": false,
                            "zChangeable": false,
                            "boundingBox": false,
                            "boundingBoxMode": "inside",
                            "autoCenter": false,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": true,
                            "colorPrices": {},
                            "colorLinkGroup": false,
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": true,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 300,
                            "left": 400,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": null,
                            "scaleMode": "fit",
                            "resizeToW": "0",
                            "resizeToH": "0",
                            "advancedEditing": false,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "customAdds": [],
                            "_isInitial": true,
                            "source": "/images/color_shirt/Shadow4.png",
                            "title": "Shadow",
                            "id": "1588100453491",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 0,
                        "removable": false,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": false,
                        "resizeToH": "0",
                        "resizeToW": "0",
                        "rotatable": false,
                        "scaleMode": "fit",
                        "scaleX": 1,
                        "scaleY": 1,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 300,
                        "topped": true,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 596,
                        "z": -1,
                        "zChangeable": false,
                        "topLeftX": 102,
                        "topLeftY": 30.5
                    },
                    "type": "image"
                }
            ],
            "options": {
                "stageWidth": 800,
                "stageHeight": 600,

                "customImageParameters": {
                    "minW": 100,
                    "minH": 100,
                    "maxW": 10000,
                    "maxH": 10000,
                    "minDPI": 72,
                    "maxSize": 10,
                    "left": 0,
                    "top": 0,
                    "z": -1,
                    "minScaleLimit": 0.01,
                    "price": 4,
                    "replaceInAllViews": false,
                    "autoCenter": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": true,
                    "autoSelect": false,
                    "topped": false,
                    "uniScalingUnlockable": false,
                    "boundingBoxMode": "inside",
                    "scaleMode": "cover",
                    "removable": true,
                    "resizeToW": "300",
                    "resizeToH": "300",
                    "advancedEditing": true,
                    "filter": "none"
                },
                "maxPrice": -1,
                "optionalView": false,
                "designCategories": [],
                "printingBox": {},
                "layouts": []
            },
        }
        var $back = {
            "title": "Back",
            "thumbnail": "/images/color_shirt/color/back/base.png",
            "elements": [
                {
                    "title": "Back Shadow",
                    "source": "/images/color_shirt/shadows2.png",
                    "parameters": {
                        "advancedEditing": false,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": "0",
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": false,
                        "colorPrices": {},
                        "colors": "",
                        "copyable": false,
                        "cornerSize": 24,
                        "draggable": false,
                        "evented": false,
                        "excludeFromExport": false,
                        "fill": false,
                        "filter": false,
                        "flipX": false,
                        "flipY": false,
                        "height": 668,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": false,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 0,
                            "price": 0,
                            "colors": "",
                            "removable": false,
                            "draggable": false,
                            "rotatable": false,
                            "resizable": false,
                            "copyable": false,
                            "zChangeable": false,
                            "boundingBox": "0",
                            "boundingBoxMode": "inside",
                            "autoCenter": false,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": false,
                            "colorPrices": {},
                            "colorLinkGroup": false,
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": false,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 316,
                            "left": 400,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": false,
                            "scaleMode": "fit",
                            "resizeToW": "0",
                            "resizeToH": "0",
                            "advancedEditing": false,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "customAdds": [],
                            "_isInitial": true,
                            "source": "/images/color_shirt/shadows2.png",
                            "title": "Back Shadow",
                            "id": "1588100453520",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 0,
                        "removable": false,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": false,
                        "resizeToH": "0",
                        "resizeToW": "0",
                        "rotatable": false,
                        "scaleMode": "fit",
                        "scaleX": 1,
                        "scaleY": 1,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 316,
                        "topped": false,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 731,
                        "z": -1,
                        "zChangeable": false,
                        "topLeftX": 34.5,
                        "topLeftY": -18
                    },
                    "type": "image"
                },
                {
                    "title": "Shirt",
                    "source": "/images/color_shirt/color/back/base.png",
                    "parameters": {
                        "advancedEditing": false,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": "0",
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": "base",
                        "colorPrices": {},
                        "colors": "",
                        "copyable": false,
                        "cornerSize": 24,
                        "draggable": false,
                        "evented": true,
                        "excludeFromExport": false,
                        "fill": $tcolor,
                        "filter": false,
                        "flipX": false,
                        "flipY": false,
                        "height": 543,
                        "isEditable": true,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": false,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 1,
                            "price": 0,
                            "colors": "",
                            "removable": false,
                            "draggable": false,
                            "rotatable": false,
                            "resizable": false,
                            "copyable": false,
                            "zChangeable": false,
                            "boundingBox": "0",
                            "boundingBoxMode": "inside",
                            "autoCenter": false,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": false,
                            "colorPrices": {},
                            "colorLinkGroup": "base",
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": false,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 300,
                            "left": 400,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": false,
                            "scaleMode": "fit",
                            "resizeToW": "0",
                            "resizeToH": "0",
                            "advancedEditing": false,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "customAdds": [],
                            "_isInitial": true,
                            "source": "/images/color_shirt/color/back/base.png",
                            "title": "Shirt",
                            "id": "1588100453544",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 0,
                        "removable": false,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": false,
                        "resizeToH": "0",
                        "resizeToW": "0",
                        "rotatable": false,
                        "scaleMode": "fit",
                        "scaleX": 1,
                        "scaleY": 1,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 300,
                        "topped": false,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 602,
                        "z": -1,
                        "zChangeable": false,
                        "topLeftX": 99,
                        "topLeftY": 28.5
                    },
                    "type": "image"
                },
                {
                    "title": "Shadow",
                    "source": "/images/color_shirt/over_shadow1.png",
                    "parameters": {
                        "advancedEditing": false,
                        "angle": 0,
                        "autoCenter": false,
                        "autoSelect": false,
                        "boundingBox": "0",
                        "boundingBoxMode": "inside",
                        "colorLinkGroup": false,
                        "colorPrices": {},
                        "colors": "",
                        "copyable": false,
                        "cornerSize": 24,
                        "draggable": false,
                        "evented": false,
                        "excludeFromExport": false,
                        "fill": false,
                        "filter": false,
                        "flipX": false,
                        "flipY": false,
                        "height": 543,
                        "left": 400,
                        "lockUniScaling": true,
                        "locked": false,
                        "minScaleLimit": 0.01,
                        "objectCaching": false,
                        "opacity": 1,
                        "originParams": {
                            "objectCaching": false,
                            "z": 2,
                            "price": 0,
                            "colors": "",
                            "removable": false,
                            "draggable": false,
                            "rotatable": false,
                            "resizable": false,
                            "copyable": false,
                            "zChangeable": false,
                            "boundingBox": "0",
                            "boundingBoxMode": "inside",
                            "autoCenter": false,
                            "replace": "",
                            "replaceInAllViews": false,
                            "autoSelect": false,
                            "topped": true,
                            "colorPrices": {},
                            "colorLinkGroup": false,
                            "patterns": [],
                            "sku": "",
                            "excludeFromExport": false,
                            "showInColorSelection": false,
                            "locked": false,
                            "uniScalingUnlockable": false,
                            "originX": "center",
                            "originY": "center",
                            "cornerSize": 24,
                            "fill": false,
                            "lockUniScaling": true,
                            "pattern": false,
                            "top": 300,
                            "left": 400,
                            "angle": 0,
                            "flipX": false,
                            "flipY": false,
                            "opacity": 1,
                            "scaleX": 1,
                            "scaleY": 1,
                            "uploadZone": false,
                            "filter": false,
                            "scaleMode": "fit",
                            "resizeToW": "0",
                            "resizeToH": "0",
                            "advancedEditing": false,
                            "uploadZoneMovable": false,
                            "uploadZoneRemovable": false,
                            "padding": 0,
                            "minScaleLimit": 0.01,
                            "customAdds": [],
                            "_isInitial": true,
                            "source": "/images/color_shirt/over_shadow1.png",
                            "title": "Shadow",
                            "id": "1588100453556",
                            "cornerColor": "#f5f5f5",
                            "cornerIconColor": "#000000",
                            "selectable": false,
                            "lockRotation": true,
                            "hasRotatingPoint": false,
                            "lockScalingX": true,
                            "lockScalingY": true,
                            "lockMovementX": true,
                            "lockMovementY": true,
                            "hasControls": false,
                            "evented": false,
                            "lockScalingFlip": true,
                            "crossOrigin": ""
                        },
                        "originX": "center",
                        "originY": "center",
                        "padding": 0,
                        "patterns": [],
                        "price": 0,
                        "removable": false,
                        "replace": "",
                        "replaceInAllViews": false,
                        "resizable": false,
                        "resizeToH": "0",
                        "resizeToW": "0",
                        "rotatable": false,
                        "scaleMode": "fit",
                        "scaleX": 1,
                        "scaleY": 1,
                        "showInColorSelection": false,
                        "sku": "",
                        "top": 300,
                        "topped": true,
                        "uniScalingUnlockable": false,
                        "uploadZone": false,
                        "uploadZoneMovable": false,
                        "uploadZoneRemovable": false,
                        "width": 602,
                        "z": -1,
                        "zChangeable": false,
                        "topLeftX": 99,
                        "topLeftY": 28.5
                    },
                    "type": "image"
                }
            ],
            "options": {
                "stageWidth": 800,
                "stageHeight": 600,
                "customAdds": {
                    "designs": true,
                    "uploads": true,
                    "texts": true,
                    "drawing": true
                },
                "customImageParameters": {
                    "minW": 100,
                    "minH": 100,
                    "maxW": 10000,
                    "maxH": 10000,
                    "minDPI": 72,
                    "maxSize": 10,
                    "left": 0,
                    "top": 0,
                    "z": -1,
                    "minScaleLimit": 0.01,
                    "price": 4,
                    "replaceInAllViews": false,
                    "autoCenter": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": true,
                    "autoSelect": false,
                    "topped": false,
                    "uniScalingUnlockable": false,
                    "boundingBoxMode": "inside",
                    "scaleMode": "cover",
                    "removable": true,
                    "resizeToW": "300",
                    "resizeToH": "300",
                    "advancedEditing": true,
                    "filter": "none"
                },
                "customTextParameters": {
                    "left": 0,
                    "top": 0,
                    "z": -1,
                    "colors": "#000",
                    "price": 2,
                    "autoCenter": true,
                    "draggable": true,
                    "rotatable": true,
                    "resizable": true,
                    "zChangeable": true,
                    "autoSelect": true,
                    "topped": false,
                    "uniScalingUnlockable": false,
                    "curvable": true,
                    "curveSpacing": 10,
                    "curveRadius": 80,
                    "curveReverse": false,
                    "boundingBoxMode": "inside",
                    "fontSize": 30,
                    "minFontSize": 1,
                    "maxFontSize": 1000,
                    "widthFontSize": 0,
                    "maxLength": 0,
                    "maxLines": 0,
                    "textAlign": "left",
                    "removable": true
                },
                "maxPrice": -1,
                "optionalView": false,
                "designCategories": [],
                "printingBox": {},
                "layouts": []
            },
            "names_numbers": null,
            "mask": null,
            "locked": false
        }
        if (false){
            var $json = [[
                $front
            ]];
        }else{
            var $json = [[
                $front,
                $back
            ]];
        }

        return $json
    }
</script>

<style lang="scss" scoped>

</style>
